### PR TITLE
Install compiler tools, clean environment

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Comment by vuillaut** [comment]
Will `make`, `cmake` and `gnuplot` come with `conda install gcc_linux-64 gxx_linux-64 gfortran_linux-64` ?

**Comment by maxnoe** [comment]
No. What do you need `cmake` `make` and `gnuplot` for?

Especially gnuplot?

**Comment by vuillaut** [comment]
Required for the C++ course.
The performances plots are made automatically with `gnuplot` once the students have run their program.

**Comment by maxnoe** [comment]
Gnuplot? When we do a scientific python course? Ok, I'll add it back.

**Comment by vuillaut** [comment]
> Gnuplot? When we do a scientific python course? Ok, I'll add it back.

Good point.
If you would like to propose an improvement in the [`C++` lecture](https://asterics2020-obelics.github.io/Lecture/CodeOptimisationAndPythonWrappers/index.html), please discuss with the author @devine73.

**Review by vuillaut — CHANGES_REQUESTED** [review]
`make`, `cmake` and `gnuplot` required for the C++ course unless I am mistaken. @devine73?

**Review by vuillaut — APPROVED** [review]

**Comment by vuillaut** [comment]
I merged so that people already installing have a cleaner install.
We can improve it later if needed.

**Pull request merged**
