### PR TITLE
Add pyscaffold to env

### PR DESCRIPTION
**Pull request by tammojan**
I'd like to use pyscaffold for the tutorial on Tuesday

### CODE REVIEW

**Comment by maxnoe** [comment]
I just looked a bit into it. It makes a lot of things, people should imho learn first before automating it.

It also does not follow best practices in some regards, e.g. adding `requirements.txt` for an installable package.

Using a `src` directory is also not very common, and there is no real reason for this in my opinion.

It also adds a ton of configuration for stuff that most projects won't need. 
Which makes it hard for newcomers to understand what is really needed and what just might be helpfull further down the road.

I don't know, what you exactly plan to show, but I think we should start with a clean state and explain how packages should look like starting from a very simple configuration, and adding step by step.

Most people are overwhelmed, when you show something this large and start explaining the single items, compared to gradually building up and explaining why this is needed or what is made easier by this.

**Comment by maxnoe** [comment]
Compare the result of running `putup test` with what the python packing guide recommends:
https://packaging.python.org/tutorials/packaging-projects/

**Comment by tammojan** [comment]
Thanks for looking into this @maxnoe! My plan was to work both bottom up (creating a project from scratch) and top down: using a template with all overwhelming possibilities like coveralls and Travis to show the possibilities you get basically for free. I'd previously considered using the template at https://github.com/NLeSC/python-template but thought pyscaffold would be better due to larger user base.  Could you suggest another template?

**Comment by maxnoe** [comment]
The cookie cutter project looks very good, minus the requirements.txt. 

There is an official sample project by PyPA here: https://github.com/pypa/sampleproject

**Pull request closed without merging**
